### ISSUE TITLE
 Method println in android.util.Log not mocked.

### ISSUE THREAD

**Issue by mustafaozhan** [touchlab/Kermit#67]
Hello 👋 

I am having exception during my test. This issue happen on `androidTest` in common module.

```
    java.lang.RuntimeException: Method println in android.util.Log not mocked. See http://g.co/androidstudio/not-mocked for details.
        at android.util.Log.println(Log.java)
        at co.touchlab.kermit.LogcatLogger.log(LogcatLogger.kt:27)
        at com.github.mustafaozhan.logmob.LogMobLogger.log(LogMobLogger.kt:26)
        at co.touchlab.kermit.Logger.d(Logger.kt:22)
        at co.touchlab.kermit.Kermit.d(Kermit.kt:43)
        at co.touchlab.kermit.Kermit.d$default(Kermit.kt:42)
        at co.touchlab.kermit.Kermit.d(Kermit.kt:47)
        at com.github.mustafaozhan.ccc.common.BaseRepositoryTest.init(BaseRepositoryTest.kt:18)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:834)

1 test completed, 1 failed
```

It happens on 

```
    @BeforeTest
    fun init() {
        application = initKoin()
        platformRepository = application.koin.get(PlatformRepository::class)
    }
```
and it has a simple logging inside.
```
fun initKoin(vararg modules: Module?) = startKoin {
    kermit.d { "initialising koin" }
    modules.forEach { it?.let { modules(it) } }
    modules(commonModule)
}
```
I know i can just remove the logging :) but just wanted to report since we may have logging in many places :) 

It only happens if I use `LogcatLogger` for android, doesn't occur if i use `CommonLogger`. 

I prefer to use LogcatLogger since it has different colors in logcat but because of this exception I am kind a forced to use CommonLogger.

**Comment by samhill303** [comment]
Logcat is an android utility which isn't available in a JUnit test. I'd suggest passing a LogcatLogger in your app, but replacing it with a CommonLogger in tests. You can see this done in KaMPKit for [Android](https://github.com/touchlab/KaMPKit/blob/0b1a956b3a0c1ee417916e3835062f55eaba78b3/shared/src/androidMain/kotlin/co/touchlab/kampkit/KoinAndroid.kt#L26) and [Tests](https://github.com/touchlab/KaMPKit/blob/0b1a956b3a0c1ee417916e3835062f55eaba78b3/shared/src/commonTest/kotlin/co/touchlab/kampkit/BreedModelTest.kt#L27). You may alternatively be able to use something like robolectric to make Logcat available in tests

**Comment by rickytribbia** [comment]
I found a simpler solution adding 

```
@BeforeTest
    fun prepareEnvironment() {
        Logger.setLogWriters(CommonWriter())
    }
```

in the test class. Could be put also into a BaseTestClass to set as default.
